### ISSUE TITLE
Optional keys as `key?: foo` rather than `key: foo: undefined`

### ISSUE THREAD

**Issue by hawkaa** [tskj/typescript-json-decoder#3]
Hi,

~Is there a way to generate decoders and types where keys are omitted if they're not present instead of being explicitly undefined?~

Is there a way to generate types from decoders where optional fields are optional keys and not keys that are required, but can be undefined?

More specifically, I'd like the type for this

```typescript
const fooDecoder = decode({
     bar: optional(string)
})
```

to be this

```typescript
type Foo = {
    bar?: string
}
```

and not this

```typescript
type Foo = {
    bar: string | undefined
}
```

It's a subtle, yet important difference here. The problem arises when I try to create objects of the types created from the decoders in my codebase. Which could be a sign of code smell, but either way, the above would be a nice feature :D

**Comment by tskj** [comment]
Well it depends on precisely what you mean. This is an issue I've struggled with since day one, and I haven't yet found a way of tricking the typesystem into generating the syntax you suggest. So it depends on what you mean by creating these objects? Are you manually creating objects that you want to decode?

I'm not sure if I'm understanding your usecase correctly, but I'm guessing you want the field `bar` to be optional (in the sense of not even specifying the key), which is very reasonable. In that case the question mark, like you suggest, might be required. There seems to have been a change in how TypeScript generates the types; the generated type used to be:

```typescript
type Foo = {
  bar?: string | undefined;
};
``` 

The `undefined` is certainly redundant and it would be cleaner without, but as I said, I haven't found a way to remove it. I see now that this might no longer be the case. But in any case, in my tests I am allowed to not specify the `bar` field, and it does still compile.

If you find a way to generate the question mark properly, I highly recommend to create a PR.

If you have some specific piece of code that does not compile, I would definitely like to see it!

**Comment by hawkaa** [comment]
Hi. Sorry for being slightly imprecise in my initial issue. I have made some clarifications in the original post.

I'm not getting the same type as you do. And my code doesn't compile. Example

```typescript
const fooDecoder = decode({
  bar: optional(string),
  baz: string,
})
type Foo = decodeType<typeof fooDecoder>
const myFoo: Foo = {
  baz: "foobar",
}
```

Error:
```sh
src/types.ts:101:7 - error TS2741: Property 'bar' is missing in type '{ baz: string; }' but required in type '{ bar: string | undefined; baz: string; }'.

101 const myFoo: Foo = {
          ~~~~~

  src/types.ts:97:3
    97   bar: optional(string),
         ~~~~~~~~~~~~~~~~~~~~~
    'bar' is declared here.
```

Typescript version 4.3.2. Could it be some compiler settings maybe?

**Comment by tskj** [comment]
Ah I see. I would suggest two changes to your code (this makes it compile on my setup, they're maybe not both necessary).

Change `decode` to be `record` for clarity. Then you need to wrap your object literal in a call to `fooDecoder`, like the following code.

```typescript
const fooDecoder = record({
  bar: optional(string),
  baz: string,
});
type Foo = decodeType<typeof fooDecoder>;
const myFoo: Foo = fooDecoder({
  baz: 'foobar',
});
```

The most important part is actually using the `fooDecoder` to decode the object, which should typecheck and compile.

**Comment by hawkaa** [comment]
Thank you.

> The most important part is actually using the fooDecoder to decode the object, which should typecheck and compile.

Yes, it compiles, but turns the errors into runtime errors. I might write `baZ` instead of `baz` and the code will compile.

**Comment by tskj** [comment]
So that's definitely true. But that's also a lot of the point, since you don't typically have the values at compiletime when they come over the network or are read from a file, which is the intended usecase of the library. If you can do checking at compiletime that's obviously a lot better, and you should do that as much as possible!

**Comment by zoul** [comment]
Oh! There’s a lot of nuance in Javascript’s handling of `undefined` ad `null`, to put it nicely :)

IMO it would be nice not having to care if a value comes from the network (through the decoder), or is constructed by hand. In my use case I would love to pretend that the types are still written by hand and not inferred from a decoder – that would feel like leaking some implementation details to their users.

Does the `--exactOptionalPropertyTypes` TypeScript switch [introduced in 4.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-4.html#exact-optional-property-types---exactoptionalpropertytypes) have anything to do with this?

**Comment by tskj** [comment]
I think that flag more or less does the exact opposite of what we want in thise case.

To reiterate my understanding of this issue, the "inferred" type (produced by the decoder) are always `{ bar: string | undefined }`, instead of a more preferable `{ bar?: string }`, which in turn forces you to type out the `bar: undefined` key in your (manual) instantiation of such an object.

I agree that this is dumb, and it was actually a design goal from the very start to produce these more desirable types (with the question marks), but I still haven't found a way to achieve this. It seems it requires some black magic to trick TypeScript to infer a question mark, if at all possible.

**Comment by zoul** [comment]
I see. Could you come up with a short, self-contained example of the inferring problem for us to play with?

**Comment by tskj** [comment]
Not sure if it's me you're asking, but the example given by @hawkaa is a good repro I think.

This doesn't compile: 
```typescript
const fooDecoder = record({
  baz: string,
  bar: optional(string),
})
type Foo = decodeType<typeof fooDecoder>;
const myFoo: Foo = {
  baz: "foobar",
}
```

But this does:
```typescript
const fooDecoder = record({
  baz: string,
  bar: optional(string),
})
type Foo = decodeType<typeof fooDecoder>;
const myFoo: Foo = {
  baz: "foobar",
  bar: undefined,
}
```

**Comment by zoul** [comment]
Sorry, I wasn’t clear enough – I meant an example not specific to this library. What kind of construct does it currently use to infer the property type?

**Comment by tskj** [comment]
Still not sure I understand your question then.

My understanding is that it's possible for a developer to write
```typescript
type Foo = {
  baz: string;
  bar?: string;
}
```

but it seems to be impossible to get TypeScript to infer a type with a question mark. That is, it will only ever give you this type:
```typescript
type Foo = {
  baz: string;
  bar: string | undefined;
}
```

**Comment by zoul** [comment]
Sorry! 🙈😁 The thing is, I don’t know how we make Typescript arrive at that `bar: string | undefined`. I’ve tried to play with the code in `types.ts` where this happens, but still don’t understand it well enough – so I am asking for a simpler example of how this code works.

(Intuitively: Is the main problem that we are defining the types recursively and when we decompose a record type into `{ [key: KeyType]: ValueType }`, we don’t know that the key is optional until we arrive at an `| undefined` later when inferring `ValueType`? It seems to me – with my current limited understanding! – that we would need to improve the line [here](https://github.com/tskj/typescript-json-decoder/blob/375c8ac9f78f37a4a2eb0dd08f84dfb8fdaaa197/src/types.ts#L48) to get a partial, [a bit like what’s described here](https://stackoverflow.com/questions/62507004/how-can-i-infer-optional-properties-in-typescript). But I could be completely off.)

**Comment by tskj** [comment]
Very interesting, I think you are on to something here. This is exactly the issue! Just for reference, if you put a question mark in that line: `{ [key: KeyType]: ValueType }` so that it becomes `{ [key: KeyType]?: ValueType }`, then every key would be optional. So this issue is all about placing the question marks "conditionally", that is, in the right spots. On first reading it seems `PartialPartial` can probably be used for this, if we are able to pick out the keys based on their `undefined`-ness.

I'll be very curious to see if you can make this work, I certainly think this is in the right direction. I will also see if I have the time to dig into it, but this really is very tricky to figure out, and takes a long time and a lot of effort.

**Comment by tskj** [comment]
I think I have finally figured this one out and have released version `1.0.8` which should address it!

 @hawkaa could you get back to me as to whether this solves your issue?

**Comment by hawkaa** [comment]
Thank you! I have unfortunately changed jobs since then, and no longer use Typescript and this library on a day-to-day basis. So I'm afraid I can't help :(

**Comment by tskj** [comment]
Alright, good luck in your new job! I'll consider this closed then.
