### ISSUE TITLE
Not sure what the key is only that its a string

### ISSUE THREAD

**Issue by Addeuz** [tskj/typescript-json-decoder#9]
Hey, we have come upon another problem.

We have a type that looks like this:
```js
export type IdentityStatus = {
  [key: string]: { status: 'Confirmed' | 'Confirmation sent' };
}

export interface IdentityConfirmations {
  boardMembersIdentity: IdentityStatus;
  beneficialOwnersIdentity: IdentityStatus;
}
```
The key in this case is a social security number but we don't know at the time of fetching this data what the SSN is. So we can't really say what the decoder should look for only that it's a string.
What I have came up with and tried is this so far:
```js
export type IdentityConfirmations = decodeType<typeof identityConfirmationsDecoder>
export const identityConfirmationsDecoder = record({
  boardMembersIdentity: record({
    ['ssn']: union('Confirmed', 'Confirmation sent'),
  }),
  beneficialOwnersIdentity: record({
    ['ssn']: union('Confirmed', 'Confirmation sent'),
  })
})
```
This doesn't seem to work like I want because the `IdentityConfirmations` type becomes this sees it like the key is `ssn` not any string..
I've tried to look at all the decoders in the source code but I can't find any that does what we want I think..

**Comment by tskj** [comment]
Interesting problem! There are a few ways to go about this from a technical perspective. Fundamentally though, I think what you have is something akin to a `Map`.

(for the record, the `{ ['ssn']: ... }` syntax in js is exactly the same as `{ ssn: ... }`, what it is good for is dynamic values - if you wanted to assign the string `'ssn'` to a variable and possibly change it at runtime, this is how you would do that)

In Typescript, there is a `Record` type, which is more or less exactly defined like `type Record<T> = { [key: string]: T }`. This describes a "record", "map" or "dictionary" (depending on what you want to call it, the point is it has keys which are strings, and there are values you can look up in it).

For this, I have implemented a decoder I have called `dict`, it is briefly described in the last part of [this section](https://github.com/tskj/typescript-json-decoder#custom-decoders) of the documentation. I will get around to elaborating on these and give them their own sections! 

The way it works is simply `const identityStatusDecoder = dict({ status: 'Confirmed' | 'Confirmation sent' })` in your case. This will match your datastructure, however it will decode *to* a `Map<string, { status: 'Confirmed' | 'Confirmation sent' }>`. I suggest actually using the `Map` datatype in your case, because what you have is in many ways really a map at heart, and not really a js-object. This means you will access the data using the regular `Map` APIs ([described here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)), such as `x.boardMembersIdentity.get(mySsn)?.status === 'Confirmed'`.

Nevertheless, if you absolutely need a `Record` type, I will consider adding another decoder for this usecase.

**Comment by Addeuz** [comment]
Yeah I figured out they where the same thing when I saw the type, that was just the last try I did haha.

We use `Map` in a big part of our codebase. So seeing it included here is interesting. I could use it this way as a map I would just have to rewrite some logic but that's fine.

I do think though that a decoder for something like a `Record` would be great! Lmk if you need help. You can reach me on andreas.johansson@diffinder.se
